spring:
  application:
    name: spring_security

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security_023
    username: postgres
    password: 8956
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: trace

server:
  port: 7999
#
#security:
#  secretKey: "sdjkfhjas1283./asd-129234][sa"
#  expiresIn: 10000